import type { Metadata } from "next";
import { cookies } from "next/headers";
import type { ReactNode } from "react";
import { ThemeInitScript } from "@/app/theme-init-script";
import { Providers } from "@/providers";
import {
  THEME_COOKIE_KEY,
  getServerResolvedTheme,
  isThemeMode,
  type ThemeMode,
} from "@/shared/theme/theme";
import "./globals.css";

export const metadata: Metadata = {
  title: "Subscription Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const cookieStore = await cookies();
  const cookieThemeMode = cookieStore.get(THEME_COOKIE_KEY)?.value;
  const initialThemeMode: ThemeMode = isThemeMode(cookieThemeMode)
    ? cookieThemeMode
    : "system";
  const serverResolvedTheme = getServerResolvedTheme(initialThemeMode);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-theme={serverResolvedTheme}
      data-theme-mode={initialThemeMode}
      className={serverResolvedTheme === "dark" ? "dark" : undefined}
    >
      <head>
        <ThemeInitScript initialThemeMode={initialThemeMode} />
      </head>
      <body>
        <Providers initialThemeMode={initialThemeMode}>{children}</Providers>
      </body>
    </html>
  );
}
