import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import type { ReactNode } from "react";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Auth | Subscription Tracker",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: ReactNode;
}) {
  const cookiesStore = await cookies();
  const refreshToken = cookiesStore.get("refreshToken");

  if (refreshToken !== undefined) {
    redirect("/account/dashboard");
  }

  return (
    <main className={styles.authContent}>
      <div className={styles.contentWrapper}>{children}</div>
    </main>
  );
}
